name: Plc Starter

on:
  push:
    branches: [ master ]
env:
      PROJECT_PATH: PlcStarter/PlcStarter.csproj
jobs:
  deploy:
    runs-on: windows-latest 

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.x

      - run: dotnet publish ${{ env.PROJECT_PATH }} -c Release -o PublishMin

      - uses: TheDoctor0/zip-release@0.6.1
        with:
          type: 'zip'
          path: PublishMin
          filename: 'PlcStarterMin.zip'

      - uses: actions/upload-artifact@v2
        with:
          name: PlcStarter Min
          path: PlcStarterMin.zip

      - run: dotnet publish ${{ env.PROJECT_PATH }} -c Release --self-contained -r win-x64 -o PublishComplete

      - uses: TheDoctor0/zip-release@0.6.1
        with:
          type: 'zip'
          path: PublishComplete
          filename: 'PlcStarterComplete.zip'

      - uses: actions/upload-artifact@v2
        with:
          name: PlcStarter Complete
          path: PlcStarterComplete.zip